# Generated by Django 4.1 on 2022-09-22 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCID', models.CharField(max_length=13)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('empDepartment', models.CharField(default=1, max_length=200)),
                ('departmentPhone', models.CharField(default='-', max_length=10)),
                ('empPhone', models.CharField(default='-', max_length=10)),
                ('empUser', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
