# Generated by Django 4.1 on 2022-09-23 14:50

from django.db import migrations
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, unique=True),
        ),
    ]
