# Generated by Django 4.1 on 2022-09-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_empuser_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='slug',
        ),
        migrations.AddField(
            model_name='empuser',
            name='empLineToken',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
