# Generated by Django 4.1 on 2022-09-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_remove_empuser_slug_empuser_emplinetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='empLineToken',
        ),
    ]
