# Generated by Django 4.1 on 2022-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_remove_empuser_emplinetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='empLineToken',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
