# Generated by Django 4.1 on 2022-09-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_empuser_emplinetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empuser',
            name='pub_date',
        ),
    ]
