# Generated by Django 4.1 on 2022-09-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_remove_empuser_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='empuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
    ]
